version: '3'

services:
  db:
    image: mysql:5.7
    container_name: mysql5
    restart: always
    environment:
      MYSQL_DATABASE: 'doctor_crud'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: 'docker'
      MYSQL_ROOT_PASSWORD: 'docker'
    ports:
      - '3306:3306'
    expose:
      - '3306'

  app:
    build:
      context: .
      dockerfile: Dockerfile-dev
    container_name: nest-app
    environment:
      - CHOKIDAR_USEPOLLING=true
    ports:
      - 3000:3000
    volumes:
      - .:/home/node/app
    links: 
      - db
