version: '3'

services:
  db:
    image: mysql:5.7
    container_name: mysql5
    restart: always
    environment:
      MYSQL_DATABASE: 'doctor_crud'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'root'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'docker'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'docker'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'

  app:
    build:
      context: .
      dockerfile: Dockerfile-dev
    container_name: nest-app
    environment:
      - CHOKIDAR_USEPOLLING=true
    ports:
      - 3000:3000
    volumes:
      - .:/home/node/app
    links: 
      - db
