 
POST http://localhost:3000/doctors
Content-type: application/json

{
    "name": "Thiago",
    "last_name": "Correia",
    "crm": "346436",
    "specialties": [1, 3]
}

###

GET http://localhost:3000/doctors

###

GET http://localhost:3000/doctors/4

###

DELETE http://localhost:3000/doctors/2