 
POST http://localhost:3000/doctors
Content-type: application/json

{
    "name": "Luiz Carlos",
    "last_name": "ALgo",
    "crm": "1234567890",
    "specialties": [1]
}

###

GET http://localhost:3000/doctors

###

GET http://localhost:3000/doctors/4

###

DELETE http://localhost:3000/doctors/2